#!/bin/sh
wget http://dl.google.com/android/android-sdk_r21.0.1-linux.tgz
tar xzf android-sdk_r21.0.1-linux.tgz

export ANDROID_HOME=`pwd`/android-sdk-linux
export PATH=${PATH}:${ANDROID_HOME}/tools:${ANDROID_HOME}/platform-tools

# Install required components.
# For a full list, run `android list sdk -a --extended`
# Note that sysimg-16 downloads the ARM, x86 and MIPS images (we should optimize this).
# Other relevant API's:
#  addon-google_apis-google-16
#
android update sdk --filter platform-tools,android-16,sysimg-16,extra-android-support --no-ui --force
